linux:
	../../bin/nitg src/app_controls.nit -m mnit_linux -o bin/controls-plain

linux-pretty:
	../../bin/nitg src/app_controls_pretty.nit -m mnit_linux -o bin/controls

android:
	../../bin/nitg src/app_controls_pretty.nit -m mnit_android -o bin/controls.apk
